# Generated by Django 5.1.1 on 2025-05-17 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=5000)),
                ('node_type', models.CharField(choices=[('api', 'API Server'), ('db', 'Database Server'), ('web', 'Web Server'), ('worker', 'Worker Node'), ('other', 'Other')], default='other', max_length=50)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_operational', models.BooleanField(default=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('nodes', models.ManyToManyField(blank=True, related_name='services', to='monitoring.node')),
            ],
        ),
    ]
